version: "3"

services:
  postgis:
    image: postgis/postgis:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autopark
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  webapp:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgis

volumes:
  pgdata:
    driver: local