# Generated by Django 3.1 on 2020-09-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
