# Generated by Django 3.1.1 on 2020-09-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20200913_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id']},
        ),
    ]
