# Generated by Django 3.1.2 on 2020-11-05 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='finished_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='route',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='track',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='VehicleMileageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], max_length=255)),
                ('started_at', models.DateField()),
                ('finished_at', models.DateField()),
                ('type', models.CharField(default='vehicle_mileage', editable=False, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
